# Site settings
title: Dan Harper
email: dan@dmuso.com
description: > # this means to ignore newlines until "baseurl:"
  Technology and Leadership.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dmuso.com" # the base hostname & protocol for your site
twitter_username: dan_harper
github_username:  dmuso

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title.html
disqus: dmuso
google_analytics: UA-69243292-1
drip: "7168585"
