---
base:
  build: .
  volumes:
    - ".:/app"
  ports:
    - "4000:4000"

web:
  extends:
    file: docker-compose.yml
    service: base
  command: ['bundle', 'exec', 'jekyll', 'server', '--source', 'source', '--destination', 'build']

jklbuild:
  extends:
    file: docker-compose.yml
    service: base
  command: ['bundle', 'exec', 'jekyll', 'build', '--source', 'source', '--destination', 'build']
