---
base:
  build: .
  volumes:
    - ".:/app"
  ports:
    - "80:4567"

web:
  extends:
    file: docker-compose.yml
    service: base
  command: ['bundle', 'exec', 'middleman', 'server']

mmbuild:
  extends:
    file: docker-compose.yml
    service: base
  command: ['bundle', 'exec', 'middleman', 'build']
