# Site settings
title: Dan Harper
email: dan@dmuso.com
description: > # this means to ignore newlines until "baseurl:"
  I am an entrepreneur, software developer and
  musician.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.dmuso.com" # the base hostname & protocol for your site
twitter_username: dan_harper
github_username:  dmuso

# Build settings
markdown: kramdown
